export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST'
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS'
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL'

export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST'
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS'
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL'
export const ORDER_DETAILS_RESET = 'ORDER_DETAILS_RESET'

export const ORDER_PAY_REQUEST = 'ORDER_PAY_REQUEST'
export const ORDER_PAY_SUCCESS = 'ORDER_PAY_SUCCESS'
export const ORDER_PAY_FAIL = 'ORDER_PAY_FAIL'
export const ORDER_PAY_RESET = 'ORDER_PAY_RESET'

export const ORDER_USER_ORDERS_LIST_REQUEST = 'ORDER_USER_ORDERS_LIST_REQUEST'
export const ORDER_USER_ORDERS_LIST_SUCCESS = 'ORDER_USER_ORDERS_LIST_SUCCESS'
export const ORDER_USER_ORDERS_LIST_FAIL = 'ORDER_USER_ORDERS_LIST_FAIL'
export const ORDER_USER_ORDERS_LIST_RESET = 'ORDER_USER_ORDERS_LIST_RESET'

export const ADMIN_ALL_ORDERS_REQUEST = 'ADMIN_ALL_ORDERS_REQUEST'
export const ADMIN_ALL_ORDERS_SUCCESS = 'ADMIN_ALL_ORDERS_SUCCESS'
export const ADMIN_ALL_ORDERS_FAIL    = 'ADMIN_ALL_ORDERS_FAIL'

export const SET_SHIPPING_DATE_ORDER_REQUEST = 'SET_SHIPPING_DATE_ORDER_REQUEST'
export const SET_SHIPPING_DATE_ORDER_SUCCESS = 'SET_SHIPPING_DATE_ORDER_SUCCESS'
export const SET_SHIPPING_DATE_ORDER_FAIL    = 'SET_SHIPPING_DATE_ORDER_FAIL'


