export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGIN_LOGOUT = 'USER_LOGIN_LOGOUT'

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'

export const USER_DETAIL_REQUEST = 'USER_DETAIL_REQUEST'
export const USER_DETAIL_FAIL = 'USER_DETAIL_FAIL'
export const USER_DETAIL_SUCCESS = 'USER_DETAIL_SUCCESS'
export const USER_DETAIL_RESET = 'USER_DETAIL_RESET'

export const USER_UPDATE_PROFILE_REQUEST = 'USER_UPDATE_PROFILE_REQUEST'
export const USER_UPDATE_PROFILE_FAIL = 'USER_UPDATE_PROFILE_FAIL'
export const USER_UPDATE_PROFILE_SUCCESS = 'USER_UPDATE_PROFILE_SUCCESS'
export const USER_UPDATE_PROFILE_RESET = 'USER_UPDATE_PROFILE_RESET'

export const USER_LIST_REQUEST = 'USER_LIST_REQUEST'
export const USER_LIST_FAIL = 'USER_LIST_FAIL'
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS'

export const USER_DELETE_REQUEST = 'USER_DELETE_REQUEST'
export const USER_DELETE_FAIL = 'USER_DELETE_FAIL'
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS'

export const USER_GETBYID_REQUEST = 'USER_GETBYID_REQUEST'
export const USER_GETBYID_FAIL = 'USER_GETBYID_FAIL'
export const USER_GETBYID_SUCCESS = 'USER_GETBYID_SUCCESS'

export const USER_GETREVIEWS_REQUEST = 'USER_GETREVIEWS_REQUEST'
export const USER_GETREVIEWS_FAIL =    'USER_GETREVIEWS_FAIL'
export const USER_GETREVIEWS_SUCCESS = 'USER_GETREVIEWS_SUCCESS'

export const USER_DELETE_REVIEW_REQUEST = 'USER_DELETE_REVIEW_REQUEST'
export const USER_DELETE_REVIEW_SUCCESS = 'USER_DELETE_REVIEW_SUCCESS'
export const USER_DELETE_REVIEW_FAIL =    'USER_DELETE_REVIEW_FAIL'
